### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by cysabi** [inkdropapp/vibrant-dark-ui#1]
This is the one extremely amazing looking theme for inkdrop. Please make it available for windows.

**Comment by craftzdog** [comment]
Thanks for the suggestion.
Unfortunately, vibrant background on Windows is not currently supported on Electron.
If it got supported, I'd be happy to make it available for Windows.

**Comment by cysabi** [comment]
Hi, it seems I have found a package that supports vibrant backgrounds on Windows 10:
https://github.com/arkenthera/electron-vibrancy

Here is a snip of the `README.md`
![image](https://user-images.githubusercontent.com/47790183/56778177-10c22580-67a3-11e9-869f-702f6474a399.png)

**Comment by craftzdog** [comment]
Yeah I know, but it seems that it is no longer maintained, unfortunately.

**Comment by craftzdog** [comment]
It's been supported as of v5.4.0
https://docs.inkdrop.app/releases/5.4.0
