### ISSUE TITLE
MacOS で v.1.3.1 で 動かすと全体的に白くなってしまう

### ISSUE THREAD

**Issue by guai3** [inkdropapp/vibrant-dark-ui#14]
v1.1.1 だと正しい見た目になりますが、v1.3.1 では白っぽくなります。
v1.1.1 で利用してるので当面は問題がないのですが、`pluin update available` の通知が気になるので、
最新バージョンも修正の修正をお願いしたいです。
https://twitter.com/ryshinoz/status/1444897844305936386?ref_src=twsrc%5Etfw

**Comment by craftzdog** [comment]
アプリのバージョン、macOSのバージョンを教えていただけますか？

**Comment by guai3** [comment]
Inkdrop は バージョン5.4.3 (5.4.3)
MacOS は バージョン 11.6 
で共に現時点で最新バージョンです。

**Comment by craftzdog** [comment]
ありがとうございます。それは奇妙ですね。
自分もmacOS 11.6 ですが、正常に動作しています。
今のところ問題の現象は手元で再現できません。
v1.1.1以前の実装はmacOSの古いAPIを使用しているため、もとに戻すことは仕様上出来ません。
他のプラグインが影響していないかなど、確認してみてください。

**Comment by craftzdog** [comment]
古い実装では動き、新しい実装では動かない事から推測するに、macOSのAppearanceをLightに設定している事が原因だと思われます。
旧APIではdarkを指定できるのですが、新APIはシステム設定に準じなければなりません。
なので、Lightモードでは残念ながらお使いいただけません。あしからずご了承ください。

**Comment by guai3** [comment]
なるほど。理解しました。
別のところで要望はあげますが、
macOSのAppearance に 同期してテーマを変更することができれば、この問題も解決すると思うので、
おいおい対応していただけるとありがたいです。

**Comment by guai3** [comment]
このプラグインを入れると、OSのAppearance  に同期してテーマを変更できたので、検索などでこのIssueを発見した他の人のためにコメントしておきます。
https://my.inkdrop.app/plugins/auto-switch-themes
