### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by InuzDev** [inkdropapp/vibrant-dark-ui#26]
Hi, I've been working today in Inkdrop and wanted to try somehow to get vibrant-dark-ui run in the demo.

I tried to build the code but found a bug due to deprecated plugins.

How to reproduce:
Use latest node package manager (npm) and install the dependencies. Try to run `npm run build` to find out browserslist isn't finding Electron and gulp is deprecated and not working as expected.

**Comment by craftzdog** [comment]
Yes, and these dependencies on gulp and others will be dropped and theming will be just a bunch of CSS variables, soon.

See the current working branch on default light UI: https://github.com/inkdropapp/inkdrop-default-light-ui-theme/blob/css-variables/styles/theme.css

**Comment by InuzDev** [comment]
Can I contribute on this? Like, help with it?

**Comment by craftzdog** [comment]
@InuDeveloper Are you on our Discord community? https://docs.inkdrop.app/start-guide/join-discord-server
I'll let you know when it's ready to work together!

**Comment by InuzDev** [comment]
@craftzdog Sadly no. I can't join.
